package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Thursday, December 3, 2015 3:14:04 PM PST
*/

public interface CalcOperations 
{
  int calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
